// Generated by Bisonc++ V4.05.00 on Wed, 25 Mar 2015 16:34:34 +0530

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them

// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <iomanip>
#include <map>
#include <fstream> 
 SymbolTableEntry* ste; SymbolTable* st; map<string, SymbolTableEntry*> paramMap; Type* retType;
 int counter_global = 0;
int offset = 0;
 std::ofstream myfile("graph.gv", std::ofstream::out | std::ofstream::app); 
 

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {301, 1}, // 1: translation_unit ->  function_definition
     {301, 2}, // 2: translation_unit ->  translation_unit function_definition
     {302, 5}, // 3: function_definition ->  type_specifier #0001 fun_declarator #0002 compound_statement
     {303, 0}, // 4: #0001 ->  <empty>
     {304, 0}, // 5: #0002 ->  <empty>
     {305, 1}, // 6: type_specifier (VOID) ->  VOID
     {305, 1}, // 7: type_specifier (INT) ->  INT
     {305, 1}, // 8: type_specifier (FLOAT) ->  FLOAT
     {306, 4}, // 9: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' parameter_list ')'
     {306, 3}, // 10: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {307, 1}, // 11: parameter_list ->  parameter_declaration
     {307, 3}, // 12: parameter_list (',') ->  parameter_list ',' parameter_declaration
     {308, 2}, // 13: parameter_declaration ->  type_specifier declarator
     {309, 1}, // 14: declarator (IDENTIFIER) ->  IDENTIFIER
     {309, 4}, // 15: declarator ('[') ->  declarator '[' constant_expression ']'
     {310, 1}, // 16: constant_expression (INT_CONSTANT) ->  INT_CONSTANT
     {310, 1}, // 17: constant_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {311, 2}, // 18: compound_statement ('{') ->  '{' '}'
     {311, 3}, // 19: compound_statement ('{') ->  '{' statement_list '}'
     {311, 4}, // 20: compound_statement ('{') ->  '{' declaration_list statement_list '}'
     {313, 1}, // 21: statement_list ->  statement
     {313, 2}, // 22: statement_list ->  statement_list statement
     {314, 3}, // 23: statement ('{') ->  '{' statement_list '}'
     {314, 1}, // 24: statement ->  selection_statement
     {314, 1}, // 25: statement ->  iteration_statement
     {314, 1}, // 26: statement ->  assignment_statement
     {314, 3}, // 27: statement (RETURN) ->  RETURN expression ';'
     {315, 1}, // 28: assignment_statement (';') ->  ';'
     {315, 4}, // 29: assignment_statement ('=') ->  l_expression '=' expression ';'
     {316, 1}, // 30: expression ->  logical_and_expression
     {316, 3}, // 31: expression (OR_OP) ->  expression OR_OP logical_and_expression
     {317, 1}, // 32: logical_and_expression ->  equality_expression
     {317, 3}, // 33: logical_and_expression (AND_OP) ->  logical_and_expression AND_OP equality_expression
     {318, 1}, // 34: equality_expression ->  relational_expression
     {318, 3}, // 35: equality_expression (EQ_OP) ->  equality_expression EQ_OP relational_expression
     {318, 3}, // 36: equality_expression (NE_OP) ->  equality_expression NE_OP relational_expression
     {319, 1}, // 37: relational_expression ->  additive_expression
     {319, 3}, // 38: relational_expression ('<') ->  relational_expression '<' additive_expression
     {319, 3}, // 39: relational_expression ('>') ->  relational_expression '>' additive_expression
     {319, 3}, // 40: relational_expression (LE_OP) ->  relational_expression LE_OP additive_expression
     {319, 3}, // 41: relational_expression (GE_OP) ->  relational_expression GE_OP additive_expression
     {320, 1}, // 42: additive_expression ->  multiplicative_expression
     {320, 3}, // 43: additive_expression ('+') ->  additive_expression '+' multiplicative_expression
     {320, 3}, // 44: additive_expression ('-') ->  additive_expression '-' multiplicative_expression
     {321, 1}, // 45: multiplicative_expression ->  unary_expression
     {321, 3}, // 46: multiplicative_expression ('*') ->  multiplicative_expression '*' unary_expression
     {321, 3}, // 47: multiplicative_expression ('/') ->  multiplicative_expression '/' unary_expression
     {322, 1}, // 48: unary_expression ->  postfix_expression
     {322, 2}, // 49: unary_expression ->  unary_operator postfix_expression
     {323, 1}, // 50: postfix_expression ->  primary_expression
     {323, 3}, // 51: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {323, 4}, // 52: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' expression_list ')'
     {323, 2}, // 53: postfix_expression (INC_OP) ->  l_expression INC_OP
     {324, 1}, // 54: primary_expression ->  l_expression
     {324, 3}, // 55: primary_expression ('=') ->  l_expression '=' expression
     {324, 1}, // 56: primary_expression (INT_CONSTANT) ->  INT_CONSTANT
     {324, 1}, // 57: primary_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {324, 1}, // 58: primary_expression (STRING_LITERAL) ->  STRING_LITERAL
     {324, 3}, // 59: primary_expression ('(') ->  '(' expression ')'
     {325, 1}, // 60: l_expression (IDENTIFIER) ->  IDENTIFIER
     {325, 4}, // 61: l_expression ('[') ->  l_expression '[' expression ']'
     {326, 1}, // 62: expression_list ->  expression
     {326, 3}, // 63: expression_list (',') ->  expression_list ',' expression
     {327, 1}, // 64: unary_operator ('-') ->  '-'
     {327, 1}, // 65: unary_operator ('!') ->  '!'
     {328, 7}, // 66: selection_statement (IF) ->  IF '(' expression ')' statement ELSE statement
     {329, 5}, // 67: iteration_statement (WHILE) ->  WHILE '(' expression ')' statement
     {329, 9}, // 68: iteration_statement (FOR) ->  FOR '(' expression ';' expression ';' expression ')' statement
     {312, 1}, // 69: declaration_list ->  declaration
     {312, 2}, // 70: declaration_list ->  declaration_list declaration
     {330, 4}, // 71: declaration (';') ->  type_specifier #0003 declarator_list ';'
     {332, 0}, // 72: #0003 ->  <empty>
     {331, 1}, // 73: declarator_list ->  declarator
     {331, 3}, // 74: declarator_list (',') ->  declarator_list ',' declarator
     {333, 1}, // 75: translation_unit_$ ->  translation_unit
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 7} },                       
    { {       301}, { 1} }, // translation_unit   
    { {       302}, { 2} }, // function_definition
    { {       305}, { 3} }, // type_specifier     
    { {       257}, { 4} }, // VOID               
    { {       258}, { 5} }, // INT                
    { {       259}, { 6} }, // FLOAT              
    { {         0}, { 0} },                       
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            7} },                       
    { {       302}, {            7} }, // function_definition
    { {       305}, {            3} }, // type_specifier     
    { {       257}, {            4} }, // VOID               
    { {       258}, {            5} }, // INT                
    { {       259}, {            6} }, // FLOAT              
    { {     _EOF_}, { PARSE_ACCEPT} },                       
    { {         0}, {            0} },                       
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { DEF_RED}, {  2} },         
    { {     303}, {  8} }, // #0001
    { {       0}, { -4} },         
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       306}, {  9} }, // fun_declarator
    { {       260}, { 10} }, // IDENTIFIER    
    { {         0}, {  0} },                  
};

SR__ s_9[] =
{
    { { DEF_RED}, {  2} },         
    { {     304}, { 11} }, // #0002
    { {       0}, { -5} },         
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 12} }, // '('
    { {         0}, {  0} },       
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  3} },                      
    { {       311}, { 13} }, // compound_statement
    { {       123}, { 14} }, // '{'               
    { {         0}, {  0} },                      
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  8} },                         
    { {       307}, { 15} }, // parameter_list       
    { {        41}, { 16} }, // ')'                  
    { {       308}, { 17} }, // parameter_declaration
    { {       305}, { 18} }, // type_specifier       
    { {       257}, {  4} }, // VOID                 
    { {       258}, {  5} }, // INT                  
    { {       259}, {  6} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, { 21} },                        
    { {       125}, { 19} }, // '}'                 
    { {       313}, { 20} }, // statement_list      
    { {       312}, { 21} }, // declaration_list    
    { {       314}, { 22} }, // statement           
    { {       330}, { 23} }, // declaration         
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       305}, { 29} }, // type_specifier      
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       257}, {  4} }, // VOID                
    { {       258}, {  5} }, // INT                 
    { {       259}, {  6} }, // FLOAT               
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 36} }, // ')'
    { {        44}, { 37} }, // ','
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       309}, { 38} }, // declarator
    { {       260}, { 39} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 40} }, // '}'                 
    { {       314}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, { 19} },                        
    { {       313}, { 42} }, // statement_list      
    { {       330}, { 43} }, // declaration         
    { {       314}, { 22} }, // statement           
    { {       305}, { 29} }, // type_specifier      
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       257}, {  4} }, // VOID                
    { {       258}, {  5} }, // INT                 
    { {       259}, {  6} }, // FLOAT               
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       313}, { 44} }, // statement_list      
    { {       314}, { 22} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 45} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_29[] =
{
    { { DEF_RED}, {   2} },         
    { {     332}, {  63} }, // #0003
    { {       0}, { -72} },         
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 64} }, // '('
    { {         0}, {  0} },       
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 65} }, // '('
    { {         0}, {  0} },       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 66} }, // '('
    { {         0}, {  0} },       
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        61}, { 67} }, // '='
    { {        91}, { 68} }, // '['
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  6} },                         
    { {       308}, { 69} }, // parameter_declaration
    { {       305}, { 18} }, // type_specifier       
    { {       257}, {  4} }, // VOID                 
    { {       258}, {  5} }, // INT                  
    { {       259}, {  6} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_38[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  70} }, // '['
    { {       0}, { -13} },       
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 71} }, // '}'                 
    { {       314}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 14} },                        
    { {       125}, { 72} }, // '}'                 
    { {       314}, { 41} }, // statement           
    { {       123}, { 24} }, // '{'                 
    { {       328}, { 25} }, // selection_statement 
    { {       329}, { 26} }, // iteration_statement 
    { {       315}, { 27} }, // assignment_statement
    { {       263}, { 28} }, // RETURN              
    { {       272}, { 30} }, // IF                  
    { {       274}, { 31} }, // WHILE               
    { {       275}, { 32} }, // FOR                 
    { {        59}, { 33} }, // ';'                 
    { {       325}, { 34} }, // l_expression        
    { {       260}, { 35} }, // IDENTIFIER          
    { {         0}, {  0} },                        
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {        59}, { 73} }, // ';'  
    { {       264}, { 74} }, // OR_OP
    { {         0}, {  0} },         
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   2} },          
    { {     265}, {  75} }, // AND_OP
    { {       0}, { -30} },          
};

SR__ s_47[] =
{
    { { REQ_DEF}, {   3} },         
    { {     266}, {  76} }, // EQ_OP
    { {     267}, {  77} }, // NE_OP
    { {       0}, { -32} },         
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  78} }, // '<'  
    { {      62}, {  79} }, // '>'  
    { {     268}, {  80} }, // LE_OP
    { {     269}, {  81} }, // GE_OP
    { {       0}, { -34} },         
};

SR__ s_49[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  82} }, // '+'
    { {      45}, {  83} }, // '-'
    { {       0}, { -37} },       
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  84} }, // '*'
    { {      47}, {  85} }, // '/'
    { {       0}, { -42} },       
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  9} },                      
    { {       323}, { 86} }, // postfix_expression
    { {       324}, { 54} }, // primary_expression
    { {       260}, { 55} }, // IDENTIFIER        
    { {       325}, { 56} }, // l_expression      
    { {       261}, { 59} }, // INT_CONSTANT      
    { {       262}, { 60} }, // FLOAT_CONSTANT    
    { {       271}, { 61} }, // STRING_LITERAL    
    { {        40}, { 62} }, // '('               
    { {         0}, {  0} },                      
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  87} }, // '('
    { {       0}, { -60} },       
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   4} },          
    { {     270}, {  88} }, // INC_OP
    { {      61}, {  89} }, // '='   
    { {      91}, {  68} }, // '['   
    { {       0}, { -54} },          
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 90} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  4} },                   
    { {       331}, { 91} }, // declarator_list
    { {       309}, { 92} }, // declarator     
    { {       260}, { 39} }, // IDENTIFIER     
    { {         0}, {  0} },                   
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 93} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 94} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 95} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 96} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, { 19} },                             
    { {       316}, { 97} }, // expression               
    { {       317}, { 46} }, // logical_and_expression   
    { {       318}, { 47} }, // equality_expression      
    { {       319}, { 48} }, // relational_expression    
    { {       320}, { 49} }, // additive_expression      
    { {       321}, { 50} }, // multiplicative_expression
    { {       322}, { 51} }, // unary_expression         
    { {       323}, { 52} }, // postfix_expression       
    { {       327}, { 53} }, // unary_operator           
    { {       324}, { 54} }, // primary_expression       
    { {       260}, { 55} }, // IDENTIFIER               
    { {       325}, { 56} }, // l_expression             
    { {        45}, { 57} }, // '-'                      
    { {        33}, { 58} }, // '!'                      
    { {       261}, { 59} }, // INT_CONSTANT             
    { {       262}, { 60} }, // FLOAT_CONSTANT           
    { {       271}, { 61} }, // STRING_LITERAL           
    { {        40}, { 62} }, // '('                      
    { {         0}, {  0} },                             
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       310}, {  98} }, // constant_expression
    { {       261}, {  99} }, // INT_CONSTANT       
    { {       262}, { 100} }, // FLOAT_CONSTANT     
    { {         0}, {   0} },                       
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  18} },                             
    { {       317}, { 101} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  17} },                             
    { {       318}, { 102} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 103} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 104} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 105} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 106} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 107} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 108} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       321}, { 109} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, {  14} },                             
    { {       321}, { 110} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       322}, { 111} }, // unary_expression  
    { {       323}, {  52} }, // postfix_expression
    { {       327}, {  53} }, // unary_operator    
    { {       324}, {  54} }, // primary_expression
    { {       260}, {  55} }, // IDENTIFIER        
    { {       325}, {  56} }, // l_expression      
    { {        45}, {  57} }, // '-'               
    { {        33}, {  58} }, // '!'               
    { {       261}, {  59} }, // INT_CONSTANT      
    { {       262}, {  60} }, // FLOAT_CONSTANT    
    { {       271}, {  61} }, // STRING_LITERAL    
    { {        40}, {  62} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  13} },                      
    { {       322}, { 112} }, // unary_expression  
    { {       323}, {  52} }, // postfix_expression
    { {       327}, {  53} }, // unary_operator    
    { {       324}, {  54} }, // primary_expression
    { {       260}, {  55} }, // IDENTIFIER        
    { {       325}, {  56} }, // l_expression      
    { {        45}, {  57} }, // '-'               
    { {        33}, {  58} }, // '!'               
    { {       261}, {  59} }, // INT_CONSTANT      
    { {       262}, {  60} }, // FLOAT_CONSTANT    
    { {       271}, {  61} }, // STRING_LITERAL    
    { {        40}, {  62} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {        41}, { 113} }, // ')'                      
    { {       326}, { 114} }, // expression_list          
    { {       316}, { 115} }, // expression               
    { {       317}, {  46} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       316}, { 116} }, // expression               
    { {       317}, {  46} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 117} }, // ')'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        59}, { 118} }, // ';'
    { {        44}, { 119} }, // ','
    { {         0}, {   0} },       
};

SR__ s_92[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  70} }, // '['
    { {       0}, { -73} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 120} }, // ')'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 121} }, // ')'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 122} }, // ';'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 123} }, // ';'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        93}, { 124} }, // ']'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 125} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_101[] =
{
    { { REQ_DEF}, {   2} },          
    { {     265}, {  75} }, // AND_OP
    { {       0}, { -31} },          
};

SR__ s_102[] =
{
    { { REQ_DEF}, {   3} },         
    { {     266}, {  76} }, // EQ_OP
    { {     267}, {  77} }, // NE_OP
    { {       0}, { -33} },         
};

SR__ s_103[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  78} }, // '<'  
    { {      62}, {  79} }, // '>'  
    { {     268}, {  80} }, // LE_OP
    { {     269}, {  81} }, // GE_OP
    { {       0}, { -35} },         
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  78} }, // '<'  
    { {      62}, {  79} }, // '>'  
    { {     268}, {  80} }, // LE_OP
    { {     269}, {  81} }, // GE_OP
    { {       0}, { -36} },         
};

SR__ s_105[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  82} }, // '+'
    { {      45}, {  83} }, // '-'
    { {       0}, { -38} },       
};

SR__ s_106[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  82} }, // '+'
    { {      45}, {  83} }, // '-'
    { {       0}, { -39} },       
};

SR__ s_107[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  82} }, // '+'
    { {      45}, {  83} }, // '-'
    { {       0}, { -40} },       
};

SR__ s_108[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  82} }, // '+'
    { {      45}, {  83} }, // '-'
    { {       0}, { -41} },       
};

SR__ s_109[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  84} }, // '*'
    { {      47}, {  85} }, // '/'
    { {       0}, { -43} },       
};

SR__ s_110[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  84} }, // '*'
    { {      47}, {  85} }, // '/'
    { {       0}, { -44} },       
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 126} }, // ')'
    { {        44}, { 127} }, // ','
    { {         0}, {   0} },       
};

SR__ s_115[] =
{
    { { REQ_DEF}, {   2} },         
    { {     264}, {  74} }, // OR_OP
    { {       0}, { -62} },         
};

SR__ s_116[] =
{
    { { REQ_DEF}, {   2} },         
    { {     264}, {  74} }, // OR_OP
    { {       0}, { -55} },         
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_118[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_119[] =
{
    { { REQ_TOKEN}, {   3} },              
    { {       309}, { 128} }, // declarator
    { {       260}, {  39} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       314}, { 129} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       328}, {  25} }, // selection_statement 
    { {       329}, {  26} }, // iteration_statement 
    { {       315}, {  27} }, // assignment_statement
    { {       263}, {  28} }, // RETURN              
    { {       272}, {  30} }, // IF                  
    { {       274}, {  31} }, // WHILE               
    { {       275}, {  32} }, // FOR                 
    { {        59}, {  33} }, // ';'                 
    { {       325}, {  34} }, // l_expression        
    { {       260}, {  35} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       314}, { 130} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       328}, {  25} }, // selection_statement 
    { {       329}, {  26} }, // iteration_statement 
    { {       315}, {  27} }, // assignment_statement
    { {       263}, {  28} }, // RETURN              
    { {       272}, {  30} }, // IF                  
    { {       274}, {  31} }, // WHILE               
    { {       275}, {  32} }, // FOR                 
    { {        59}, {  33} }, // ';'                 
    { {       325}, {  34} }, // l_expression        
    { {       260}, {  35} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_122[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       316}, { 131} }, // expression               
    { {       317}, {  46} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_123[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_125[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_126[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_127[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       316}, { 132} }, // expression               
    { {       317}, {  46} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_128[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, {  70} }, // '['
    { {       0}, { -74} },       
};

SR__ s_129[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       273}, { 133} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_131[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        59}, { 134} }, // ';'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_132[] =
{
    { { REQ_DEF}, {   2} },         
    { {     264}, {  74} }, // OR_OP
    { {       0}, { -63} },         
};

SR__ s_133[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       314}, { 135} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       328}, {  25} }, // selection_statement 
    { {       329}, {  26} }, // iteration_statement 
    { {       315}, {  27} }, // assignment_statement
    { {       263}, {  28} }, // RETURN              
    { {       272}, {  30} }, // IF                  
    { {       274}, {  31} }, // WHILE               
    { {       275}, {  32} }, // FOR                 
    { {        59}, {  33} }, // ';'                 
    { {       325}, {  34} }, // l_expression        
    { {       260}, {  35} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       316}, { 136} }, // expression               
    { {       317}, {  46} }, // logical_and_expression   
    { {       318}, {  47} }, // equality_expression      
    { {       319}, {  48} }, // relational_expression    
    { {       320}, {  49} }, // additive_expression      
    { {       321}, {  50} }, // multiplicative_expression
    { {       322}, {  51} }, // unary_expression         
    { {       323}, {  52} }, // postfix_expression       
    { {       327}, {  53} }, // unary_operator           
    { {       324}, {  54} }, // primary_expression       
    { {       260}, {  55} }, // IDENTIFIER               
    { {       325}, {  56} }, // l_expression             
    { {        45}, {  57} }, // '-'                      
    { {        33}, {  58} }, // '!'                      
    { {       261}, {  59} }, // INT_CONSTANT             
    { {       262}, {  60} }, // FLOAT_CONSTANT           
    { {       271}, {  61} }, // STRING_LITERAL           
    { {        40}, {  62} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {   3} },         
    { {        41}, { 137} }, // ')'  
    { {       264}, {  74} }, // OR_OP
    { {         0}, {   0} },         
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  13} },                        
    { {       314}, { 138} }, // statement           
    { {       123}, {  24} }, // '{'                 
    { {       328}, {  25} }, // selection_statement 
    { {       329}, {  26} }, // iteration_statement 
    { {       315}, {  27} }, // assignment_statement
    { {       263}, {  28} }, // RETURN              
    { {       272}, {  30} }, // IF                  
    { {       274}, {  31} }, // WHILE               
    { {       275}, {  32} }, // FOR                 
    { {        59}, {  33} }, // ';'                 
    { {       325}, {  34} }, // l_expression        
    { {       260}, {  35} }, // IDENTIFIER          
    { {         0}, {   0} },                        
};

SR__ s_138[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,
};

typedef std::unordered_map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "_UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "_EOF_"),
    SMapVal(256, "_error_"),

    SMapVal(257, "VOID"),
    SMapVal(258, "INT"),
    SMapVal(259, "FLOAT"),
    SMapVal(260, "IDENTIFIER"),
    SMapVal(261, "INT_CONSTANT"),
    SMapVal(262, "FLOAT_CONSTANT"),
    SMapVal(263, "RETURN"),
    SMapVal(264, "OR_OP"),
    SMapVal(265, "AND_OP"),
    SMapVal(266, "EQ_OP"),
    SMapVal(267, "NE_OP"),
    SMapVal(268, "LE_OP"),
    SMapVal(269, "GE_OP"),
    SMapVal(270, "INC_OP"),
    SMapVal(271, "STRING_LITERAL"),
    SMapVal(272, "IF"),
    SMapVal(273, "ELSE"),
    SMapVal(274, "WHILE"),
    SMapVal(275, "FOR"),
    SMapVal(276, "OTHER"),
    SMapVal(277, "SYMBOL"),
    SMapVal(301, "translation_unit"),
    SMapVal(302, "function_definition"),
    SMapVal(303, "#0001"),
    SMapVal(304, "#0002"),
    SMapVal(305, "type_specifier"),
    SMapVal(306, "fun_declarator"),
    SMapVal(307, "parameter_list"),
    SMapVal(308, "parameter_declaration"),
    SMapVal(309, "declarator"),
    SMapVal(310, "constant_expression"),
    SMapVal(311, "compound_statement"),
    SMapVal(312, "declaration_list"),
    SMapVal(313, "statement_list"),
    SMapVal(314, "statement"),
    SMapVal(315, "assignment_statement"),
    SMapVal(316, "expression"),
    SMapVal(317, "logical_and_expression"),
    SMapVal(318, "equality_expression"),
    SMapVal(319, "relational_expression"),
    SMapVal(320, "additive_expression"),
    SMapVal(321, "multiplicative_expression"),
    SMapVal(322, "unary_expression"),
    SMapVal(323, "postfix_expression"),
    SMapVal(324, "primary_expression"),
    SMapVal(325, "l_expression"),
    SMapVal(326, "expression_list"),
    SMapVal(327, "unary_operator"),
    SMapVal(328, "selection_statement"),
    SMapVal(329, "iteration_statement"),
    SMapVal(330, "declaration"),
    SMapVal(331, "declarator_list"),
    SMapVal(332, "#0003"),
    SMapVal(333, "translation_unit_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(true),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}

// $insert debugfunctions

std::ostringstream ParserBase::s_out__;

std::ostream &ParserBase::dflush__(std::ostream &out)
{
    std::ostringstream &s_out__ = dynamic_cast<std::ostringstream &>(out);

    std::cout << "    " << s_out__.str() << std::flush;
    s_out__.clear();
    s_out__.str("");
    return out;
}

std::string ParserBase::stype__(char const *pre, STYPE__ const &semVal, char const *post) const
{
    return "";
}
std::string ParserBase::symbol__(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << "`" << it->second << "'";
    else if (isprint(value))
        ostr << "`" << static_cast<char>(value) << "' (" << value << ")";
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << "'";
    return ostr.str();
}


Meta__::SType ParserBase::d_val__;
void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert debug
    if (d_debug__)
        s_out__ <<   "push(state " << state << stype__(", semantic TOS = ", d_val__, ")") << ')' << "\n" << dflush__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(" << count << ") from stack having size " << (d_stackIdx__ + 1) << "\n" << dflush__;
    if (d_stackIdx__ < static_cast<int>(count))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "Terminating parse(): unrecoverable input error at token " << symbol__(d_token__) << "\n" << dflush__;
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert debug
    if (d_debug__)
        s_out__ <<  "pop(): next state: " << d_state__ << ", token: " << symbol__(d_token__) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  stype__("semantic: ", d_val__) << "\n" << dflush__;
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    // $insert debug
    if (d_debug__)
        s_out__ <<  "executeAction(): of rule " << production ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic [TOS]: ", d_val__) << " ..." << "\n" << dflush__;
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 23 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[0].data<Tag__::stmtAst>();
         cout << "printing: ";
         d_val__.get<Tag__::stmtAst>()->print();
         cout << endl;
         }
        break;

        case 2:
#line 30 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new Seq(d_vsp__[-1].data<Tag__::stmtAst>(), d_vsp__[0].data<Tag__::stmtAst>());
         }
        break;

        case 3:
#line 49 "parse.y"
        {
         st->localVariables = paramMap;
         d_val__.get<Tag__::stmtAst>() = d_vsp__[0].data<Tag__::stmtAst>();
         st->Print();
         
         }
        break;

        case 4:
#line 37 "parse.y"
        d_val__ = d_vsp__[0];
        {
         st = new SymbolTable();
         st->retType = d_vsp__[0].data<Tag__::type>();
         }
        break;

        case 5:
#line 42 "parse.y"
        d_val__ = d_vsp__[-2];
        {
         st->funcName = d_vsp__[0].data<Tag__::String>();
         st->parameters = paramMap;
         paramMap.clear();
         offset = 0;
         }
        break;

        case 6:
#line 59 "parse.y"
        {
         d_val__.get<Tag__::type>() = new Type(Kind::Base, Basetype::Void);
         
         }
        break;

        case 7:
#line 64 "parse.y"
        {
         d_val__.get<Tag__::type>() = new Type(Kind::Base, Basetype::Int); 
         
         }
        break;

        case 8:
#line 69 "parse.y"
        {
         d_val__.get<Tag__::type>() = new Type(Kind::Base, Basetype::Float); 
         
         }
        break;

        case 9:
#line 76 "parse.y"
        {d_val__.get<Tag__::String>() = d_vsp__[-3].data<Tag__::String>();}
        break;

        case 10:
#line 77 "parse.y"
        {d_val__.get<Tag__::String>() = d_vsp__[-2].data<Tag__::String>();}
        break;

        case 13:
#line 86 "parse.y"
        {
         SymbolTableEntry* ste = new SymbolTableEntry(12, d_vsp__[-1].data<Tag__::type>());
         paramMap[((Index *)d_vsp__[0].data<Tag__::expAst>())->identifier_name] = ste;
         }
        break;

        case 14:
#line 94 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new Index(d_vsp__[0].data<Tag__::String>());
         }
        break;

        case 15:
#line 98 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new Index((Index*)d_vsp__[-3].data<Tag__::expAst>(), d_vsp__[-1].data<Tag__::expAst>(), true); 
         }
        break;

        case 16:
#line 105 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new IntConst(d_vsp__[0].data<Tag__::Int>());
         }
        break;

        case 17:
#line 109 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new FloatConst(d_vsp__[0].data<Tag__::Float>());
         }
        break;

        case 18:
#line 116 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new BlockStatement();
         }
        break;

        case 19:
#line 120 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[-1].data<Tag__::stmtAst>();
         }
        break;

        case 20:
#line 124 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[-1].data<Tag__::stmtAst>();
         }
        break;

        case 21:
#line 131 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new BlockStatement(d_vsp__[0].data<Tag__::stmtAst>());
         }
        break;

        case 22:
#line 135 "parse.y"
        {
         ((BlockStatement*)d_vsp__[-1].data<Tag__::stmtAst>())->children.push_back(d_vsp__[0].data<Tag__::stmtAst>());
         d_val__.get<Tag__::stmtAst>() = d_vsp__[-1].data<Tag__::stmtAst>();
         }
        break;

        case 23:
#line 143 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[-1].data<Tag__::stmtAst>();
         }
        break;

        case 24:
#line 147 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[0].data<Tag__::stmtAst>();
         }
        break;

        case 25:
#line 151 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[0].data<Tag__::stmtAst>();
         }
        break;

        case 26:
#line 155 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = d_vsp__[0].data<Tag__::stmtAst>();
         }
        break;

        case 27:
#line 159 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new Return(d_vsp__[-1].data<Tag__::expAst>());
         }
        break;

        case 28:
#line 166 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new Ass();
         }
        break;

        case 29:
#line 170 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new Ass(d_vsp__[-3].data<Tag__::expAst>(), d_vsp__[-1].data<Tag__::expAst>());
         }
        break;

        case 30:
#line 177 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 31:
#line 181 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::OR);
         }
        break;

        case 32:
#line 188 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 33:
#line 192 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::AND);
         }
        break;

        case 34:
#line 199 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 35:
#line 203 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::EQ_OP);
         }
        break;

        case 36:
#line 207 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::NE_OP);
         }
        break;

        case 37:
#line 213 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 38:
#line 217 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::LT);
         }
        break;

        case 39:
#line 221 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::GT);
         }
        break;

        case 40:
#line 225 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::LE_OP);
         }
        break;

        case 41:
#line 229 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::GE_OP);
         }
        break;

        case 42:
#line 236 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 43:
#line 240 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::PLUS);
         }
        break;

        case 44:
#line 244 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::MINUS);
         }
        break;

        case 45:
#line 251 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>(); 
         }
        break;

        case 46:
#line 255 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::MULT);
         }
        break;

        case 47:
#line 259 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::MULT);
         }
        break;

        case 48:
#line 265 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 49:
#line 269 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpUnary(d_vsp__[-1].data<Tag__::expAst>(), (OpUnary*)d_vsp__[0].data<Tag__::expAst>());
         }
        break;

        case 50:
#line 276 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>(); 
         }
        break;

        case 51:
#line 280 "parse.y"
        {
         
         d_val__.get<Tag__::expAst>() = new Funcall(new Identifier(d_vsp__[-2].data<Tag__::String>()));
         }
        break;

        case 52:
#line 285 "parse.y"
        {
         ((Funcall*)d_vsp__[-1].data<Tag__::expAst>())->children.insert(((Funcall*)d_vsp__[-1].data<Tag__::expAst>())->children.begin(), new Identifier(d_vsp__[-3].data<Tag__::String>()));
         d_val__.get<Tag__::expAst>() = d_vsp__[-1].data<Tag__::expAst>();
         }
        break;

        case 53:
#line 290 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpUnary(d_vsp__[-1].data<Tag__::expAst>(), opNameU::PP);
         }
        break;

        case 54:
#line 297 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[0].data<Tag__::expAst>();
         }
        break;

        case 55:
#line 301 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpBinary(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::expAst>(), opNameB::ASSIGN);
         }
        break;

        case 56:
#line 305 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new IntConst(d_vsp__[0].data<Tag__::Int>()); 
         }
        break;

        case 57:
#line 309 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new FloatConst(d_vsp__[0].data<Tag__::Float>()); 
         }
        break;

        case 58:
#line 313 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new StringConst(d_vsp__[0].data<Tag__::String>()); 
         }
        break;

        case 59:
#line 317 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = d_vsp__[-1].data<Tag__::expAst>();
         }
        break;

        case 60:
#line 324 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new Identifier(d_vsp__[0].data<Tag__::String>());
         }
        break;

        case 61:
#line 328 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new Index((ArrayRef*)d_vsp__[-3].data<Tag__::expAst>(), d_vsp__[-1].data<Tag__::expAst>(), false);
         }
        break;

        case 62:
#line 334 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new Funcall(d_vsp__[0].data<Tag__::expAst>());
         }
        break;

        case 63:
#line 338 "parse.y"
        {
         ((Funcall*)d_vsp__[-2].data<Tag__::expAst>())->children.push_back(d_vsp__[0].data<Tag__::expAst>());
         d_val__.get<Tag__::expAst>() = d_vsp__[-2].data<Tag__::expAst>();
         }
        break;

        case 64:
#line 345 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpUnary(opNameU::UMINUS); 
         }
        break;

        case 65:
#line 349 "parse.y"
        {
         d_val__.get<Tag__::expAst>() = new OpUnary(opNameU::NOT); 
         }
        break;

        case 66:
#line 356 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new If(d_vsp__[-4].data<Tag__::expAst>(), d_vsp__[-2].data<Tag__::stmtAst>(), d_vsp__[0].data<Tag__::stmtAst>());
         }
        break;

        case 67:
#line 363 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new While(d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::stmtAst>());
         }
        break;

        case 68:
#line 367 "parse.y"
        {
         d_val__.get<Tag__::stmtAst>() = new For(d_vsp__[-6].data<Tag__::expAst>(), d_vsp__[-4].data<Tag__::expAst>(), d_vsp__[-2].data<Tag__::expAst>(), d_vsp__[0].data<Tag__::stmtAst>());
         }
        break;

        case 69:
#line 374 "parse.y"
        {
         
         }
        break;

        case 70:
#line 378 "parse.y"
        {
         
         
         }
        break;

        case 71:
#line 390 "parse.y"
        {
         
         }
        break;

        case 72:
#line 386 "parse.y"
        d_val__ = d_vsp__[0];
        {
         retType = d_vsp__[0].data<Tag__::type>();
         }
        break;

        case 73:
#line 396 "parse.y"
        {
         paramMap[((Index *)d_vsp__[0].data<Tag__::expAst>())->identifier_name] = new SymbolTableEntry(offset, retType->copy());
         offset += retType->size();
         }
        break;

        case 74:
#line 400 "parse.y"
        {
         paramMap[((Index *)d_vsp__[0].data<Tag__::expAst>())->identifier_name] = new SymbolTableEntry(offset, retType->copy());
         offset += retType->size();
         }
        break;

    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "... action of rule " << production << " completed" ;
    // $insert debug
    if (d_debug__)
        s_out__ <<   stype__(", semantic: ", d_val__) << "\n" << dflush__;
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

    // $insert debug
    if (d_debug__)
        s_out__ <<  "reduce(): by rule " << (&pi - s_productionInfo) ;
    // $insert debug
    if (d_debug__)
        s_out__ <<  " to N-terminal " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
        // $insert debug
        if (d_debug__)
            s_out__ <<  "nextToken(): popped " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
    // $insert debug
    if (d_debug__)
        s_out__ <<  "nextToken(): using " << symbol__(d_token__) << stype__(", semantic = ", d_val__) << "\n" << dflush__;
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "): default reduction by rule " << -elementPtr->d_action << "\n" << dflush__;
            return elementPtr->d_action;                
        }
        // $insert debug
        if (d_debug__)
            s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__) << "): Not " ;
        // $insert debug
        if (d_debug__)
            s_out__ <<  "found. " << (recovery ? "Continue" : "Start") << " error recovery."  << "\n" << dflush__;

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;

// $insert debuglookup
    if (d_debug__)
    {
        s_out__ <<  "lookup(" << d_state__ << ", " << symbol__(d_token__);

        if (action < 0)             // a reduction is found
            s_out__ << "): reduce by rule " << -action;
        else if (action == 0)
            s_out__ <<  "): ACCEPT";
        else 
            s_out__ <<  "): shift " << action << " (" << symbol__(d_token__) << 
                        " processed)";

        s_out__ << "\n" << dflush__;
    }

    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }

    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): " << d_nErrors__ << " error(s) so far. State = " << top__() << "\n" << dflush__;

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "errorRecovery(): pop state " << top__() << "\n" << dflush__;
        pop__();
    }
    // $insert debug
    if (d_debug__)
        s_out__ <<  "errorRecovery(): state " << top__() << " is an ERROR state" << "\n" << dflush__;

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() SHIFT state " << action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", continue with " << symbol__(d_token__) << "\n" << dflush__;

                if (gotToken)
                {
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  "errorRecovery() COMPLETED: next state " ;
                    // $insert debug
                    if (d_debug__)
                        s_out__ <<  action << ", no token yet" << "\n" << dflush__;

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
                // $insert debug
                if (d_debug__)
                    s_out__ <<  "errorRecovery() REDUCE by rule " << -action ;
                // $insert debug
                if (d_debug__)
                    s_out__ <<  ", token = " << symbol__(d_token__) << "\n" << dflush__;
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): Parsing starts" << "\n" << dflush__;
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        // $insert debug
        if (d_debug__)
            s_out__ <<  "==" << "\n" << dflush__;
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    // $insert debug
    if (d_debug__)
        s_out__ <<  "parse(): returns " << retValue << "\n" << dflush__;
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}




